=== luisloyola/PODA/PODA/PODA-web/validator.dtd
<!ELEMENT comenzar (objeto)>
<!ELEMENT objeto (escena+)>
<!ELEMENT escena (bloque+)>
<!ELEMENT bloque (idea+)>
<!ELEMENT idea (texto*, voz)>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT voz (#PCDATA)>

<!ATTLIST objeto titulo CDATA #REQUIRED>
<!ATTLIST objeto autor CDATA #REQUIRED>
<!ATTLIST objeto tema CDATA #REQUIRED>
<!ATTLIST escena titulo CDATA #REQUIRED>
<!ATTLIST escena tipo CDATA #REQUIRED>

<!ATTLIST idea ordenAparicion CDATA #REQUIRED>
<!ATTLIST texto tipo CDATA #REQUIRED>

=== luisloyola/PODA/PODA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comenzar SYSTEM "validator.dtd"> 

<comenzar>
	<objeto titulo="Prueba v3" autor="Probador" tema="default">
		<escena titulo="Escena 1 Columna" tipo="1Col">
			<bloque>
				<idea ordenAparicion="1">
					<texto tipo="normal">texto 1Col: 1</texto>
					<texto tipo="codigo">texto 1Col: 2 </texto>
					<voz>Voz 1Col</voz>
				</idea>
			</bloque>
		</escena>
		<escena titulo="Escena 1 Fila 2 Columnas" tipo="1Fil2Col">
			<bloque>
				<idea ordenAparicion="1">
					<texto tipo="ejemplo">texto 1Row2Col: 1</texto>
					<texto tipo="manuscrito">texto 1Row2Col: 2</texto>
					<voz>Voz 1Row2Col</voz>
				</idea>
			</bloque>	
			<bloque>
				<idea ordenAparicion="2">
					<texto tipo="normal">texto 1Row2Col: 3</texto>
					<texto tipo="manuscrito">texto 1Row2Col: 4</texto>
					<voz>Voz 1Row2Col</voz>
				</idea>
			</bloque>
			<bloque>
				<idea ordenAparicion="3">
					<texto tipo="ejemplo">texto 1Row2Col: 5</texto>
					<texto tipo="ejemplo">texto 1Row2Col: 6</texto>
					<voz>Voz 1Row2Col</voz>
				</idea>
			</bloque>		
		</escena>
		<escena titulo="Escena 2 Columnas" tipo="2Col">
			<bloque>
				<idea ordenAparicion="1">
					<texto tipo="normal">texto 1Row2Col: 1</texto>
					<texto tipo="codigo">texto 1Row2Col: 2</texto>
					<voz>Voz 1Row2Col</voz>
				</idea>
			</bloque>	
			<bloque>
				<idea ordenAparicion="2">
					<texto tipo="manuscrito">texto 1Row2Col: 3</texto>
					<texto tipo="manuscrito">texto 1Row2Col: 4</texto>
					<voz>Voz 1Row2Col</voz>
				</idea>
			</bloque>
		</escena>
		<escena titulo="Escena 3 Columnas" tipo="3Col">
			<bloque>
				<idea ordenAparicion="1">
					<texto tipo="codigo">texto 3Col: 1</texto>
					<texto tipo="codigo">texto 3Col: 2</texto>
					<voz>Voz 3Col</voz>
				</idea>
			</bloque>
			<bloque>
				<idea ordenAparicion="2">
					<texto tipo="manuscrito">texto 3Col: 3</texto>
					<texto tipo="codigo">texto 3Col: 4</texto>
					<voz>Voz 3Col</voz>
				</idea>
			</bloque>
			<bloque>
				<idea ordenAparicion="3">
					<texto tipo="normal">texto 3Col: 5</texto>
					<texto tipo="normal">texto 3Col: 6</texto>
					<voz>Voz 3Col</voz>
				</idea>
			</bloque>
		</escena>
		<escena titulo="Escena 1 Fila 3 Columnas" tipo="1Fil3Col">
			<bloque>
				<idea ordenAparicion="1">
					<texto tipo="normal">texto 1Row3Col: 1</texto>
					<texto tipo="codigo">texto 1Row3Col: 2</texto>
					<voz>Voz 1Row3Col</voz>
				</idea>
			</bloque>
			<bloque>
				<idea ordenAparicion="2">
					<texto tipo="normal">texto 1Row3Col: 3</texto>
					<texto tipo="normal">texto 1Row3Col: 4</texto>
					<voz>Voz 1Row3Col</voz>
				</idea>
			</bloque>
			<bloque>
				<idea ordenAparicion="3">
					<texto tipo="normal">texto 1Row3Col: 5</texto>
					<texto tipo="codigo">texto 1Row3Col: 6</texto>
					<voz>Voz 1Row3Col</voz>
				</idea>
			</bloque>
			<bloque>
				<idea ordenAparicion="4">
					<texto tipo="normal">texto 1Row3Col: 7</texto>
					<texto tipo="normal">texto 1Row3Col: 8</texto>
					<voz>Voz 1Row3Col</voz>
				</idea>
			</bloque>
		</escena>
		<escena titulo="Escena 2 Filas 2 Columnas" tipo="2Fil2Col">
			<bloque>
				<idea ordenAparicion="1">
					<texto tipo="normal">texto 2Row2Col: 1</texto>
					<texto tipo="normal">texto 2Row2Col: 2</texto>
					<voz>Voz 2Row2Col</voz>
				</idea>
			</bloque>
			<bloque>
				<idea ordenAparicion="2">
					<texto tipo="normal">texto 2Row2Col: 3</texto>
					<texto tipo="normal">texto 2Row2Col: 4</texto>
					<voz>Voz 2Row2Col</voz>
				</idea>
			</bloque>
			<bloque>
				<idea ordenAparicion="3">
					<texto tipo="normal">texto 2Row2Col: 5</texto>
					<texto tipo="manuscrito">texto 2Row2Col: 6</texto>
					<voz>Voz 2Row2Col</voz>
				</idea>
			</bloque>
			<bloque>
				<idea ordenAparicion="4">
					<texto tipo="normal">texto 2Row2Col: 7</texto>
					<texto tipo="normal">texto 2Row2Col: 8</texto>
					<voz>Voz 2Row2Col</voz>
				</idea>
			</bloque>
		</escena>
	</objeto>
</comenzar>
